server:
  port: 8080
  servlet:
    context-path: /spring
spring:
  datasource:
    driverClassName: "com.mysql.cj.jdbc.Driver"
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/libary-service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nd1242003@gmail.com
    password: dpsl uyxt rqhj vgzn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  scheduling:
    thread-pool:
      size: 1
jwt:
  signerKey: "qNgTMRm3ljcHlDua2vu4x/ydt+TrH+9e/YqR7z9vRB/yCkprX/UfQuOVCiIGNFwE"
  valid-duration: 3600
  refreshable-duration: 36000

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: 4CGC8HI1
    secretKey: FF7ID9KXB5IV6O5X4UA47ELTMCB1T5CO
    returnUrl: http://localhost:8080/spring/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other
